### ISSUE TITLE
In Mattermost 4.2+, seems to return JSON into Mattermost conversation

### ISSUE THREAD

**Issue by dniesen** [miquels/mm-memebot#1]
Example, when typing an invalid meme, the following is returned to the channel/conversation:

```
{
            "response_type": "ephemeral",
            "text": "meme not found\ntry: /meme list"
        }
```

When typing a valid meme (ie: /meme yuno;wtf;wtf), receive this:

```
{
        "response_type": "in_channel",
        "text": "image"
    }
```

And then the image shows up overlaid on it.
![mm-memebot-json](https://user-images.githubusercontent.com/22966652/32123768-0ce9f56c-bb2b-11e7-95e6-2a29234a9a37.png)

**Comment by dniesen** [comment]
This appears to be related to a [breaking change](https://docs.mattermost.com/administration/changelog.html#breaking-changes):

> 1 - Mattermost now handles multiple content types for integrations, including plaintext content type. If your integration suddenly prints the JSON payload data instead of rendering the generated message, make sure your integration is returning the application/json content-type to retain previous behavior.

**Comment by martintrojer** [comment]
#2 fixes this issue

**Comment by miquels** [comment]
I'm upgrading this week to the latest mattermost myself (we were still running 4.0), so this patch is welcome. Thanks :)
